import "../styles/global.scss";
import AuthContex from "./context/AuthContext";
export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <AuthContex>
                <body>{children}</body>
            </AuthContex>
        </html>
    );
}
