import Head from 'next/head'
import { Header } from '../components/header'
import { NavBar } from '../components/navBar'
import { RestaurantCard } from '../components/RestaurantCard';
import { PrismaClient, Cuisine, Location, PRICE, User, Review } from '@prisma/client';
import styles from '../styles/home.module.scss'
import { notFound } from 'next/navigation';

export interface RestaurantCardType{
  id: number,
  name: string,
  main_image: string,
  slug: string,
  cuisine: Cuisine,
  location: Location,
  price: PRICE
  review: Review[]
}

const prisma = new PrismaClient();

const fetchRestaurants = async (): Promise<RestaurantCardType[]> => {
  const restaurants = await prisma.restaurant.findMany({
    select: {
      id: true,
      name: true,
      main_image: true,
      cuisine: true,
      location: true,
      price: true,
      review: true,
      slug: true,
    }
  })
  if(!restaurants){
    notFound()
  }
  return restaurants
}

export default async function Home() {
const restaurants = await fetchRestaurants();

  return (
    <>

        <Head>
        <title>Open</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet"></link>
      
        </Head>

      <main className={styles.mainContainer}>
        <main className={styles.SecondMainContainer}>

            <NavBar/>
            <main>
            <Header/>
            </main>
            <div className={styles.RestaurantCardWrapper}>
            {restaurants.map((restaurant) =>(
              <RestaurantCard restaurant={restaurant}
                                key={restaurant.id}/>
            ))}

            </div >
        </main>
        </main>
    </>
  )
}
